# Site Info
title:              "Nicklas Larsen - Content creator"
description:        "The personal blog for budding author Nicklas Larsen. Contains fiction, life blog, and advice."
author:             "Nicklas Larsen"
author_email:       "blog@nila.io"
google_analytics:   UA-79601385-1 # Put your Google Analytics code
logo:               /assets/favicon.png

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
url:                "http://nila.io"
permalink:          /:title # Post permalink
timezone:           Europe/Copenhagen # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:               [jekyll-sitemap, jekyll-seo-tag]

# Social media
twitter:
    username: iNicklasLarsen
facebook:
    app_id: 283219398693979
    publisher: 300541510288649
    admins: 1609051390
twitter_username: iNicklasLarsen
youtube_username: https://www.youtube.com/channel/UCpIZlLB9P3YFvEdKRc-2JQw
facebook_username: iNicklasLarsen

compress_html:
    clippings:      all
    ignore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
